---
- hosts: all_servers
  remote_user: ec2-user
  become: true
  vars:
    doc_root: /home/ec2-user
    installs_folder: /opt/custom
    region: us-east-1
    domain: vladimir.com
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts



    - name: copy nginx site.conf
      template:
        src: site.conf.j2
        dest: /etc/nginx/conf.d/{{ domain }}
        owner: root
        group: root
        mode: '0644'

    - name: restart nginx
      service:
        name: nginx
        state: restarted
